FROM debian:latest

MAINTAINER Dilawar Singh <dilawar.s.rajput@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

WORKDIR /work

# Always runs from top-directory
ADD . /work

RUN apt update
RUN apt -y install libgdal-dev python3-dev python3-pip g++ gcc
RUN pip install pip --upgrade
RUN ls -R
