name: Linux

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install -y libgdal-dev python3-gdal python3-numpy
        python -m pip install --upgrade pip wheel setuptools poetry
        poetry install
    - name: Lint and type checking
      run: |
        poetry run mypy --install-types --non-interactive epimargin
        poetry run mypy --ignore-missing-imports epimargin
        poetry run pylint -E epimargin
    - name: Test with pytest
      run: |
        poetry run pytest tests
